# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 13:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('qty_offered', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name=b'Quantity Offered')),
                ('qty_wanted', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name=b'Quantity Wanted')),
                ('item_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.Item')),
                ('item_wanted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_username', models.CharField(max_length=100)),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Platform')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Platform'),
        ),
        migrations.AddField(
            model_name='offer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Player'),
        ),
        migrations.AddField(
            model_name='bid',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Offer'),
        ),
        migrations.AddField(
            model_name='bid',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Player'),
        ),
    ]
