# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
