# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_player_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, max_length=10000)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Bid')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Player')),
            ],
        ),
    ]
