# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20161002_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
